name: Build Windows
on:
  push:
    branches: [ main, master, actions ]
  pull_request:
    branches: [ main, master, actions ]
  workflow_dispatch:

concurrency:
  group: environment-win-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    name: Build - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            name: "Windows x64 MSVC"
            artifact: "Windows-MSVC.tar.xz"
            build_type: "RelWithDebInfo"
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
            cc: "cl"
            cxx: "cl"
            archiver: "7z a"
            generators: "Visual Studio 17 2022"
            build_dir: 'build'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: hybrik
          python-version: 3.8

      - name: Build HybrIK
        shell: bash
        run: |
          # 1. Create a conda virtual environment.
          # conda create -n hybrik python=3.8 -y
          # conda activate hybrik

          # 2. Install PyTorch
          conda install pytorch==1.9.1 torchvision==0.10.1 -c pytorch

          # 3. Install PyTorch3D (Optional, only for visualization)
          # conda install -c fvcore -c iopath -c conda-forge fvcore iopath
          # conda install -c bottler nvidiacub
          # pip install git+ssh://git@github.com/facebookresearch/pytorch3d.git@stable

          # 4. Pull our code
          git clone https://github.com/Jeff-sjtu/HybrIK.git
          cd HybrIK

          # 5. Install
          pip install pycocotools
          python setup.py develop  # or "pip install -e ."

      - name: Handle Error
        uses: Silverlan/common_actions/action_handle_error@main
        if: failure()
